name: Run Instagram Scraper Hourly

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run script
        run: |
          python scraper.py
          # python googlenews.py
          # python fb.py
          # python rssfeed.py
          # python fbtime.py
          # python trends.py
